version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: "glennrobinsononline.com"
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - npm run-script build
  post_build:
    on-failure: ABORT
    commands:
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - aws cloudfront create-invalidation --distribution-id E1REPJ9MCVVYQB --paths '/*'
      - echo Build completed on `date`
artifacts:
  files:
    - 'dist/*'
  discard-paths: yes